services:
  registry:
    image: registry:2
    container_name: registry
    restart: always
     ports:
      - "500:500"
    environment:
      REGISTRY_HTTP_ADDR: 0.0.0.0:5000
    volumes:
      - ./data:/var/lib/registry

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    environment:
      DOMAIN: ${DOMAIN}
    volumes:
      - ./certs:/etc/nginx/certs:ro
      - ./nginx.conf:/etc/nginx/templates/default.conf.template:ro
