services:
  registry:
    image: registry:2
    restart: always
    environment:
      REGISTRY_HTTP_ADDR: 0.0.0.0:5000
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/fullchain.pem
      REGISTRY_HTTP_TLS_KEY: /certs/privkey.pem
    volumes:
      - ./data:/var/lib/registry
      - ./certs:/certs
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - 80:80
      - 443:443
    environment:
      DOMAIN: ${DOMAIN}
    volumes:
      - ./certs:/etc/nginx/certs:ro
      - ./nginx.conf:/etc/nginx/templates/default.conf.template:ro
